version: "3.8"
services:
  my-node-app:
    build: .
    ports:
      - 3333:4000/tcp
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - Z:\plexConfig:/config
      - Z:\Videos\VHS2\VHS-Finished:/videos:ro
