version: '3.8'
services:
  my-node-app:
    container_name: node
    build: .
    restart: unless-stopped
    ports:
      - 3333:4000/tcp
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    networks:
      - bmg
    links:
      - redis

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./mongo-db:/data/db
      # - mongo-db:/data/db
    networks:
      - bmg
    links:
      - redis

  redis:
    container_name: redis
    image: redis
    networks:
      - bmg

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - Z:\plexConfig:/config
      - Z:\Videos\VHS2\VHS-Finished:/homeVideos:ro

# volumes:
#   mongo-db:
networks:
  bmg:
    external: true
